---
apache_packages: [ 'apache2', 'unzip' ]
php_packages: [ 'php', 'libapache2-mod-php', 'php-mysql', 'php-intl', 'php-mbstring', 'php-xml', 'php-zip', 'php-imap', 'php-gd', 'php-ldap' ]
apache_mods: [ 'rewrite','ssl' ]