---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalar Apache
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ apache_packages }}"

- name: Instalar PHP + dependencias
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ php_packages }}"

- name: Descarga y descomprime limesurvey
  ansible.builtin.unarchive:
    src: "{{ lime_url }}"
    dest: /var/www/html
    remote_src: true
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"

- name: Configurando sitio
  ansible.builtin.template:
    src: "files/limesurvey.conf.j2"
    dest: "/etc/apache2/sites-available/{{ sitio_conf }}"

- name: Limpiando y habilitando modulos PHP
  ansible.builtin.shell: |
    /usr/sbin/a2dissite 000-default.conf
    /usr/bin/rm /var/www/html/index.html
    a2enmod rewrite

- name: Activar sitio
  ansible.builtin.shell: /usr/sbin/a2ensite {{ sitio_conf }}
  notify: servicios_apache